### ISSUE TITLE
Privacy policy link does not work

### ISSUE THREAD

**Issue by andrazznidar** [beemdevelopment/website#2]
"Privacy Policy" at the bottom of the [website](https://getaegis.app/) links to [https://beem.dev/aegis/privacy.html](https://beem.dev/aegis/privacy.html)
This URL does not load for me (DNS server returns SERVFAIL).

The correct url is probably [https://getaegis.app/aegis/privacy.html](https://getaegis.app/aegis/privacy.html).

**Comment by alexbakker** [comment]
Fixed by 003943ffd7fe1361fd3d01a487ba80236c72ae62.
