### ISSUE TITLE
Link to Google Play should start with https://

### ISSUE THREAD

**Issue by andrazznidar** [beemdevelopment/website#4]
Current link to Google Play is [**http://** play.google.com/store/apps/details?id=com.beemdevelopment.aegis](http://play.google.com/store/apps/details?id=com.beemdevelopment.aegis)

The URL should start with **https** to reduce the attack surface.
[https://play.google.com/store/apps/details?id=com.beemdevelopment.aegis](https://play.google.com/store/apps/details?id=com.beemdevelopment.aegis)

**Comment by alexbakker** [comment]
Fixed by 43a80c3355c8602b6b6d9f9fb444f73a8921a237.
